local opt = vim.opt

opt.hidden = true -- Required to keep multiple buffers open multiple buffers
opt.wrap = true -- Display long lines as just one line
opt.encoding = "utf-8" -- The encoding displayed
opt.fileencoding = "utf-8" -- The encoding written to file
opt.ruler = true -- Show the cursor position all the time
opt.cmdheight = 2 -- More space for displaying messages
opt.iskeyword = opt.iskeyword + "-" -- treat dash separated words as a word text object"
opt.mouse = "a" -- Enable your mouse
opt.splitbelow = true -- Horizontal splits will automatically be below
opt.splitright = true -- Vertical splits will automatically be to the right
opt.tabstop = 4 -- Insert 2 spaces for a tab
opt.shiftwidth = 2 -- Change the number of space characters inserted for indentation
opt.smarttab = true -- Makes tabbing smarter will realize you have 2 vs 4
opt.shortmess = opt.shortmess + "c" -- Don't pass messages to |ins-completion-menu|.
opt.signcolumn = "yes"
opt.smartindent = true -- Makes indenting smart
opt.autoindent = true -- Good auto indent
opt.laststatus = 2 -- Always display the status line
opt.number = true -- Line numbers
opt.relativenumber = true -- Relative line numbers
opt.cursorline = true -- Enable highlighting of the current line
-- opt.background = "dark"                 -- tell vim what the background color looks like
opt.showtabline = 2 -- Always show tabs
opt.showmode = false -- We don't need to see things like -- INSERT -- anymore
opt.backup = false -- This is recommended by coc
opt.writebackup = false -- This is recommended by coc
opt.updatetime = 50 -- Faster completion
opt.timeoutlen = 500 -- By default timeoutlen is 1000 ms
-- opt.clipboard = "unnamedplus"           -- Copy paste between vim and everything else
-- opt.autochdir = true                    -- Your working directory will always be the same as your working directory
opt.listchars = "tab:>-,trail:~,extends:>,precedes:<,space:·"
opt.completeopt = "menu,menuone,noselect"
opt.list = true
opt.background = "dark"
opt.termguicolors = true
opt.hlsearch = false
opt.inccommand = "split"
opt.undofile = true
opt.showcmd = false
opt.foldlevel = 20
opt.foldmethod = "expr"
opt.foldexpr = "nvim_treesitter#foldexpr()"
opt.wildmenu = true
opt.wildmode = "longest:list,full"
opt.expandtab = true
